/**
 * Merchant name → category ID mapping.
 * Keys are lowercase, normalized merchant substrings.
 * Merged with the main keywordMap at runtime by the Enricher.
 */
export const merchantCategoryMap: Record<string, string> = {
  // ── Food & Dining ──────────────────────────────────────────────────────────
  swiggy: "food",
  zomato: "food",
  "pizza hut": "food",
  pizzahut: "food",
  dominos: "food",
  "domino's": "food",
  mcdonalds: "food",
  "mcdonald's": "food",
  kfc: "food",
  "burger king": "food",
  burgerking: "food",
  subway: "food",
  starbucks: "food",
  "cafe coffee day": "food",
  ccd: "food",
  dunkin: "food",
  "baskin robbins": "food",
  "barbeque nation": "food",
  "box8": "food",
  "faasos": "food",
  "freshmenu": "food",
  "haldiram": "food",
  "paradise biryani": "food",
  "behrouz biryani": "food",
  "biryani by kilo": "food",
  "wow momo": "food",
  "chaayos": "food",
  "chai point": "food",
  "la pino'z": "food",
  lapinoz: "food",
  "oven story": "food",
  ovenstory: "food",
  eatsure: "food",
  "rebel foods": "food",
  "hunger box": "food",
  hungerbox: "food",
  "mad over donuts": "food",
  "krispy kreme": "food",

  // ── Groceries ─────────────────────────────────────────────────────────────
  bigbasket: "groceries",
  "big basket": "groceries",
  "grofers": "groceries",
  blinkit: "groceries",
  zepto: "groceries",
  "dunzo daily": "groceries",
  "jio mart": "groceries",
  jiomart: "groceries",
  "nature's basket": "groceries",
  "more supermarket": "groceries",
  "d-mart": "groceries",
  dmart: "groceries",
  "star bazaar": "groceries",
  "spencer's": "groceries",
  spencers: "groceries",
  "reliance fresh": "groceries",
  "reliance smart": "groceries",
  "easy day": "groceries",
  "smart bazaar": "groceries",
  "v-mart": "groceries",
  vmart: "groceries",
  "hypercity": "groceries",
  "spar": "groceries",
  supr: "groceries",
  milkbasket: "groceries",
  "country delight": "groceries",
  countrydelight: "groceries",

  // ── Transport ─────────────────────────────────────────────────────────────
  uber: "transport",
  ola: "transport",
  "ola cabs": "transport",
  rapido: "transport",
  "meru cabs": "transport",
  "bluesmart": "transport",
  indrive: "transport",
  "uber auto": "transport",
  "ola auto": "transport",
  "yulu": "transport",
  bounce: "transport",
  vogo: "transport",
  "metro rail": "transport",
  "delhi metro": "transport",
  "mumbai metro": "transport",
  irctc: "transport",
  "indian railways": "transport",
  "redbus": "transport",
  "abhibus": "transport",
  makemytrip: "transport",
  "make my trip": "transport",
  goibibo: "transport",
  "paytm travel": "transport",
  iocl: "transport",
  "indian oil": "transport",
  "hp petrol": "transport",
  hpcl: "transport",
  bpcl: "transport",
  "bharat petroleum": "transport",
  "shell petrol": "transport",
  essar: "transport",
  fastag: "transport",
  "netc fastag": "transport",

  // ── Entertainment ─────────────────────────────────────────────────────────
  netflix: "entertainment",
  "amazon prime": "entertainment",
  "prime video": "entertainment",
  hotstar: "entertainment",
  "disney+ hotstar": "entertainment",
  "disney hotstar": "entertainment",
  "jio cinema": "entertainment",
  jiocinema: "entertainment",
  "sony liv": "entertainment",
  sonyliv: "entertainment",
  "zee5": "entertainment",
  "alt balaji": "entertainment",
  voot: "entertainment",
  mxplayer: "entertainment",
  "mx player": "entertainment",
  "apple tv": "entertainment",
  spotify: "entertainment",
  "apple music": "entertainment",
  "jio saavn": "entertainment",
  "wynk music": "entertainment",
  gaana: "entertainment",
  "hungama music": "entertainment",
  bookmyshow: "entertainment",
  "book my show": "entertainment",
  "pvr cinemas": "entertainment",
  "inox movies": "entertainment",
  "cinepolis": "entertainment",
  "carnival cinemas": "entertainment",
  youtube: "entertainment",
  twitch: "entertainment",
  steam: "entertainment",
  "epic games": "entertainment",
  "google play": "entertainment",

  // ── Shopping ──────────────────────────────────────────────────────────────
  amazon: "shopping",
  "amazon.in": "shopping",
  flipkart: "shopping",
  myntra: "shopping",
  ajio: "shopping",
  nykaa: "shopping",
  "nykaa fashion": "shopping",
  meesho: "shopping",
  snapdeal: "shopping",
  shopclues: "shopping",
  tatacliq: "shopping",
  "tata cliq": "shopping",
  "reliance digital": "shopping",
  "croma": "shopping",
  "vijay sales": "shopping",
  "ezone": "shopping",
  "lifestyle stores": "shopping",
  lifestyle: "shopping",
  pantaloons: "shopping",
  westside: "shopping",
  "max fashion": "shopping",
  "h&m": "shopping",
  zara: "shopping",
  uniqlo: "shopping",
  "marks & spencer": "shopping",
  "marks and spencer": "shopping",
  levi: "shopping",
  "peter england": "shopping",
  "van heusen": "shopping",
  "raymond": "shopping",
  "fabindia": "shopping",
  "bata": "shopping",
  "metro shoes": "shopping",
  "liberty shoes": "shopping",
  "woodland": "shopping",
  "decathlon": "shopping",
  "puma": "shopping",
  "nike": "shopping",
  "adidas": "shopping",
  "reebok": "shopping",
  "ikea": "shopping",
  "hometown": "shopping",
  pepperfry: "shopping",
  "urban ladder": "shopping",

  // ── Health ────────────────────────────────────────────────────────────────
  "apollo pharmacy": "health",
  "apollo hospitals": "health",
  apollo: "health",
  "medplus": "health",
  "netmeds": "health",
  "pharmeasy": "health",
  "1mg": "health",
  "tata 1mg": "health",
  practo: "health",
  "manipal hospital": "health",
  "fortis": "health",
  "max hospital": "health",
  "narayana health": "health",
  "columbia asia": "health",
  "care hospital": "health",
  "thyrocare": "health",
  "dr lal pathlabs": "health",
  "srl diagnostics": "health",
  "healthians": "health",
  "portea": "health",
  cult: "health",
  "cult.fit": "health",
  "gold's gym": "health",
  goldsgym: "health",
  "anytime fitness": "health",
  "fitness first": "health",
  fitternity: "health",

  // ── Utilities ─────────────────────────────────────────────────────────────
  "tata power": "utilities",
  "bses": "utilities",
  "adani electricity": "utilities",
  "torrent power": "utilities",
  "bescom": "utilities",
  "msedcl": "utilities",
  "tneb": "utilities",
  "cesc": "utilities",
  airtel: "utilities",
  "jio": "utilities",
  "vi ": "utilities",
  "vodafone idea": "utilities",
  "bsnl": "utilities",
  "tata sky": "utilities",
  "dish tv": "utilities",
  "sun direct": "utilities",
  "hathway": "utilities",
  "act fibernet": "utilities",
  "you broadband": "utilities",
  "tikona": "utilities",
  "mahanagar gas": "utilities",
  "indraprastha gas": "utilities",
  "gail gas": "utilities",
  "gujarat gas": "utilities",
  "piped gas": "utilities",

  // ── Travel ────────────────────────────────────────────────────────────────
  "air india": "travel",
  indigo: "travel",
  "spicejet": "travel",
  "vistara": "travel",
  "air asia": "travel",
  "go air": "travel",
  "akasa air": "travel",
  "oyo rooms": "travel",
  oyo: "travel",
  treebo: "travel",
  "fab hotels": "travel",
  fabhotels: "travel",
  "taj hotels": "travel",
  "marriott": "travel",
  "hyatt": "travel",
  "oberoi": "travel",
  "itc hotels": "travel",
  "cleartrip": "travel",
  yatra: "travel",
  "via.com": "travel",
  "ease my trip": "travel",
  easemytrip: "travel",

  // ── Salary / Income ───────────────────────────────────────────────────────
  salary: "salary",
  payroll: "salary",
  "neft cr": "salary",
  stipend: "salary",
  "freelance payment": "business",
  upwork: "business",
  fiverr: "business",
  razorpay: "business",
  cashfree: "business",
  payu: "business",
};

export function normalizeMerchant(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9\s]/g, "").trim();
}

export function lookupMerchantCategory(merchant: string): string | null {
  const normalized = normalizeMerchant(merchant);
  // Exact match first
  if (merchantCategoryMap[normalized]) return merchantCategoryMap[normalized];
  // Substring match
  for (const [key, catId] of Object.entries(merchantCategoryMap)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return catId;
    }
  }
  return null;
}
